# Generated by Django 4.0.4 on 2022-05-29 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('director_name', models.CharField(max_length=100)),
                ('num_critic_for_reviews', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('director_facebook_likes', models.IntegerField()),
                ('actor_3_facebook_likes', models.IntegerField()),
                ('actor_2_name', models.CharField(max_length=100)),
                ('actor_1_facebook_likes', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('actor_1_name', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=100)),
                ('num_voted_users', models.IntegerField()),
                ('cast_total_facebook_likes', models.IntegerField()),
                ('actor_3_name', models.CharField(max_length=100)),
                ('facenumber_in_poster', models.IntegerField()),
                ('movie_imdb_link', models.CharField(max_length=100)),
                ('num_user_for_reviews', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('content_rating', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('title_year', models.IntegerField()),
                ('actor_2_facebook_likes', models.IntegerField()),
                ('imdb_score', models.FloatField()),
                ('aspect_ratio', models.FloatField()),
                ('movie_facebook_likes', models.IntegerField()),
                ('popularity', models.FloatField()),
                ('genres', models.ManyToManyField(to='goal.genre')),
                ('plot_keywords', models.ManyToManyField(to='goal.keyword')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['movie_title'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.users')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.ManyToManyField(through='goal.Rating', to='goal.users'),
        ),
    ]
